export default result = [
    {
        id: "464416",
        name: "Mehfil",
        cloudinaryImageId: "xb2nbyytblwf2jdfdicc",
        locality: "Kv Road No 12",
        areaName: "Banjara Hills",
        costForTwo: "₹300 for two",
        cuisines: ["Biryani", "Chinese", "Kebabs", "Tandoor"],
        avgRating: 4.3,
        parentId: "637",
        avgRatingString: "4.3",
        deliveryTime: 33,
    },
    {
        id: "237054",
        name: "Cafe Bahar since 1973",
        cloudinaryImageId: "h5k3lxdgmoi8bcfo5kgs",
        locality: "Ops zone to Himayth Nagar",
        areaName: "Basheer Bagh",
        costForTwo: "₹300 for two",
        cuisines: ["Biryani", "Chinese", "Indian", "Kebabs", "Tandoor"],
        avgRating: 4.3,
        parentId: "316607",
        avgRatingString: "4.3",
        deliveryTime: 15,
    },
    {
        id: "13552",
        name: "Shadab Go",
        cloudinaryImageId:
            "FOOD_CATALOG/IMAGES/CMS/2024/8/24/fefecbb2-1c7c-4466-b5a5-f2098f2a70d4_5fad0267-877f-4074-8001-7297f73b8e01.jpg",
        locality: "Banjara Hills",
        areaName: "Banjara Hills",
        costForTwo: "₹500 for two",
        cuisines: ["Biryani", "Chinese", "Haleem"],
        avgRating: 4.2,
        parentId: "8347",
        avgRatingString: "4.2",
        deliveryTime: 38,
    },
    {
        id: "142670",
        name: "Shah Ghouse Hotel & Restaurant",
        cloudinaryImageId: "grqh1zb1kv8uhkmyercb",
        locality: "Santh Nirankari Satsang Bhavan",
        areaName: "Banjara Hills",
        costForTwo: "₹350 for two",
        cuisines: ["Biryani", "Chinese", "Tandoor", "Mughlai"],
        avgRating: 4.3,
        parentId: "19271",
        avgRatingString: "4.3",
        totalRatingsString: "64K+",
        deliveryTime: 23,
    },
    {
        id: "6994",
        name: "Santosh Dhaba Exclusive",
        cloudinaryImageId: "e85994f6c2636cd7ffd082e2020d1847",
        locality: "Abids",
        areaName: "ABids",
        costForTwo: "₹300 for two",
        cuisines: ["Biryani", "Chinese", "Italian", "Mexican", "Desserts"],
        avgRating: 4.3,
        parentId: "8784",
        avgRatingString: "4.3",
        deliveryTime: 27,
    },
    {
        id: "4138",
        name: "Grand Hotel",
        cloudinaryImageId: "qtda4lwfmlwweg3ecibu",
        locality: "Banjara Hills",
        areaName: "Abids",
        costForTwo: "₹300 for two",
        cuisines: ["Biryani", "Chinese", "Kebabs", "Tandoor"],
        avgRating: 4.4,
        parentId: "4001",
        avgRatingString: "4.4",
        deliveryTime: 25,
    },
    {
        id: "2796",
        name: "Blue Fox",
        cloudinaryImageId:
            "FOOD_CATALOG/IMAGES/CMS/2024/4/23/2549c862-7abb-4c69-8d00-4761b7c5c734_25c6ddcd-d758-4cec-8a16-17c3b92953f9.jpg_compressed",
        locality: "Himayath Nagar",
        areaName: "Himayathnagar",
        costForTwo: "₹800 for two",
        cuisines: ["Biryani", "Chinese", "Tandoor"],
        avgRating: 4.3,
        parentId: "48033",
        avgRatingString: "4.3",
        deliveryTime: 23,
    },
];
